lbx_run({
  'grade_a',                  @() lbx_str_eq('A', grade(95))
  'grade_boundary_ninety',    @() lbx_str_eq('A', grade(90))
  'grade_b',                  @() lbx_str_eq('B', grade(85))
  'grade_c',                  @() lbx_str_eq('C', grade(70))
  'grade_d',                  @() lbx_str_eq('D', grade(60))
  'grade_f',                  @() lbx_str_eq('F', grade(59))
  'grade_zero_is_f',          @() lbx_str_eq('F', grade(0))
  'grade_hundred_is_a',       @() lbx_str_eq('A', grade(100))
  'grade_rejects_negative',   @() lbx_error('grade:range', @() grade(-1))
  'grade_rejects_over_100',   @() lbx_error('grade:range', @() grade(101))
  'sign_negative',            @() lbx_str_eq('negative', describe_sign(-3))
  'sign_zero',                @() lbx_str_eq('zero', describe_sign(0))
  'sign_positive',            @() lbx_str_eq('positive', describe_sign(3))
  'sign_of_a_fraction',       @() lbx_str_eq('negative', describe_sign(-0.001))
  'sum_until_stops_in_time',  @() lbx_eq(6, total_of([1 2 3 4], 6))
  'sum_until_counts_used',    @() lbx_eq(3, used_of([1 2 3 4], 6))
  'sum_until_takes_all',      @() lbx_eq(6, total_of([1 2 3], 100))
  'sum_until_takes_none',     @() lbx_eq(0, total_of([10 1], 5))
  'sum_until_used_is_zero',   @() lbx_eq(0, used_of([10 1], 5))
  'sum_until_stops_not_skips',@() lbx_eq(1, used_of([1 10 1], 5))
  'sum_until_exact_limit',    @() lbx_eq(5, total_of([5 1], 5))
  'sum_until_of_empty',       @() lbx_eq(0, total_of([], 5))
});
