lbx_run({
  'stats_mean',               @() lbx_near(3, summary_stats([1 2 6]).avg)
  'stats_median',             @() lbx_near(2, summary_stats([1 2 6]).med)
  'stats_median_of_even',     @() lbx_near(2.5, summary_stats([1 2 3 4]).med)
  'stats_std_is_the_sample',  @() lbx_near(1, summary_stats([1 2 3]).sd)
  'stats_range',              @() lbx_near(5, summary_stats([1 2 6]).rng)
  'stats_of_a_constant',      @() lbx_near(0, summary_stats([4 4 4]).sd)
  'stats_of_a_matrix',        @() lbx_near(2.5, summary_stats([1 2; 3 4]).avg)
  'stats_of_one',             @() lbx_near(7, summary_stats(7).avg)
  'stats_of_empty_throws',    @() lbx_error('summary_stats:empty', @() summary_stats([]))
  'top_n_takes_the_largest',  @() lbx_eq([90; 80], top_n(scores(), 'Score', 2).Score)
  'top_n_orders_descending',  @() lbx_true(top_n(scores(), 'Score', 3).Score(1) >= top_n(scores(), 'Score', 3).Score(2))
  'top_n_returns_a_table',    @() lbx_type('table', top_n(scores(), 'Score', 1))
  'top_n_keeps_every_column', @() lbx_eq(2, width(top_n(scores(), 'Score', 1)))
  'top_n_moves_whole_rows',   @() lbx_str_eq('cat', top_n(scores(), 'Score', 1).Name{1})
  'top_n_past_the_end',       @() lbx_eq(4, height(top_n(scores(), 'Score', 99)))
  'top_n_of_one',             @() lbx_eq(1, height(top_n(scores(), 'Score', 1)))
  'save_bar_writes_a_png',    @() lbx_true(bar_is_png())
  'save_bar_without_labels',  @() lbx_true(bar_bytes_unlabelled() > 1000)
  'save_bar_closes_its_figure', @() lbx_eq(0, bar_figures_left())
});
