lbx_run({
  "makes_a_string_from_char",     @() lbx_str_eq("hi", char(string("hi")))
  "class_is_string_not_char",     @() lbx_type("string", string("hi"))
  "a_char_is_not_a_string",       @() lbx_false(ischar(string("hi")))
  "strlength_counts_characters",  @() lbx_eq(5, strlength(string("hello")))
  "strlength_over_an_array",      @() lbx_eq([1 2], strlength(string({"a","bb"})))
  "length_is_the_element_count",  @() lbx_eq(2, length(string({"a","bb"})))
  "size_of_an_array",             @() lbx_eq([1 2], size(string({"a","bb"})))
  "plus_concatenates",            @() lbx_str_eq("ab", char(string("a") + string("b")))
  "plus_accepts_a_char",          @() lbx_str_eq("ab", char(string("a") + "b"))
  "plus_scalar_expands",          @() lbx_eq([1 1], double(strlength(string({"x","y"}) + "") > 0))
  "equality_by_value",            @() lbx_true(string("a") == string("a"))
  "inequality",                   @() lbx_true(string("a") ~= string("b"))
  "eq_over_an_array",             @() lbx_eq(logical([1 0]), string({"a","b"}) == "a")
  "ordinal_less_than",            @() lbx_true(string("apple") < string("banana"))
  "contains",                     @() lbx_true(contains(string("hello"), "ell"))
  "contains_is_false_when_absent",@() lbx_false(contains(string("hello"), "xyz"))
  "startsWith_and_endsWith",      @() lbx_true(startsWith(string("hello"), "he") && endsWith(string("hello"), "lo"))
  "upper_and_lower",              @() lbx_str_eq("HI", char(upper(string("hi"))))
  "strtrim",                      @() lbx_str_eq("hi", char(strtrim(string("  hi  "))))
  "replace",                      @() lbx_str_eq("hAllo", char(replace(string("hello"), "e", "A")))
  "reverse",                      @() lbx_str_eq("cba", char(reverse(string("abc"))))
  "split_returns_an_array",       @() lbx_eq(3, length(split(string("a,b,c"), ",")))
  "split_keeps_the_pieces",       @() lbx_str_eq("b", char(split(string("a,b,c"), ","){2}))
  "join_puts_them_back",          @() lbx_str_eq("a-b-c", char(join(split(string("a,b,c"), ","), "-")))
  "indexing_one_element",         @() lbx_str_eq("b", char(string({"a","b","c"})(2)))
  "indexing_with_end",            @() lbx_str_eq("c", char(string({"a","b","c"})(end)))
  "logical_indexing",             @() lbx_eq(2, length(string({"a","b","c"})(logical([1 0 1]))))
  "double_parses_numbers",        @() lbx_near(3.5, double(string("3.5")))
  "string_from_a_number",         @() lbx_str_eq("42", char(string(42)))
  "isempty_of_a_real_string",     @() lbx_false(isempty(string("a")))
  "horzcat_builds_an_array",      @() lbx_eq(2, length([string("a"), string("b")]))
  "rejects_a_bad_type",           @() lbx_error("string:badInput", @() string(struct("a",1)))
  "rejects_mismatched_sizes",     @() lbx_error("string:sizeMismatch", @() string({"a","b"}) + string({"x","y","z"}))
});
