mk = @() categorical({"red","blue","red","green","blue","red"});
sz = categorical({"small","large","medium"}, {"small","medium","large"}, {}, "Ordinal", true);

lbx_run({
  "class_is_categorical",        @() lbx_type("categorical", mk())
  "length_counts_values",        @() lbx_eq(6, length(mk()))
  "categories_are_sorted",       @() lbx_eq({"blue";"green";"red"}, categories(mk()))
  "countcats_counts_each",       @() lbx_eq([2 1 3], countcats(mk()))
  "countcats_lines_up_with_cats",@() lbx_eq(numel(categories(mk())), numel(countcats(mk())))
  "iscategory",                  @() lbx_true(iscategory(mk(), "red"))
  "iscategory_false",            @() lbx_false(iscategory(mk(), "purple"))
  "equality_against_text",       @() lbx_eq(logical([1 0 1 0 0 1]), mk() == "red")
  "inequality",                  @() lbx_eq(3, sum(mk() ~= "red"))
  "cellstr_round_trip",          @() lbx_str_eq("blue", cellstr(mk()){2})
  "double_gives_the_codes",      @() lbx_eq(6, numel(double(mk())))
  "codes_are_category_indices",  @() lbx_true(all(double(mk()) >= 1 & double(mk()) <= 3))
  "indexing_one_value",          @() lbx_str_eq("red", char(mk()(1)))
  "indexing_with_end",           @() lbx_str_eq("red", char(mk()(end)))
  "logical_indexing",            @() lbx_eq(3, length(mk()(mk() == "red")))
  "a_value_outside_the_set",     @() lbx_true(isundefined(categorical({"x"}, {"a","b"})))
  "undefined_is_not_a_category", @() lbx_eq(0, double(categorical({"x"}, {"a","b"})))
  "fixed_valueset_keeps_unused", @() lbx_eq(3, numel(categories(categorical({"a"}, {"a","b","c"}))))
  "unused_category_counts_zero", @() lbx_eq([1 0 0], countcats(categorical({"a"}, {"a","b","c"})))
  "removecats_drops_unused",     @() lbx_eq(1, numel(categories(removecats(categorical({"a"}, {"a","b","c"})))))
  "removecats_keeps_values",     @() lbx_str_eq("a", char(removecats(categorical({"a"}, {"a","b","c"}))))
  "removecats_named",            @() lbx_eq(2, numel(categories(removecats(categorical({"a","b"}, {"a","b","c"}), "c"))))
  "addcats_extends_the_set",     @() lbx_eq(4, numel(categories(addcats(mk(), "purple"))))
  "renamecats_one",              @() lbx_true(iscategory(renamecats(mk(), "red", "crimson"), "crimson"))
  "renamecats_changes_values",   @() lbx_str_eq("crimson", char(renamecats(mk(), "red", "crimson")(1)))
  "ordinal_less_than",           @() lbx_true(sz(1) < sz(2))
  "ordinal_greater_than",        @() lbx_true(sz(2) > sz(3))
  "ordinal_order_is_the_valueset",@() lbx_true(sz(3) > sz(1))
  "unordered_refuses_comparison",@() lbx_error("categorical:notOrdinal", @() mk()(1) < mk()(2))
  "duplicate_category_rejected", @() lbx_error("categorical:duplicateCategory", @() categorical({"a"}, {"a","a"}))
  "wrong_name_count_rejected",   @() lbx_error("categorical:nameCount", @() categorical({"a"}, {"a","b"}, {"x"}))
  "brace_indexing_refused",      @() lbx_error("categorical:braceIndex", @() mk(){1})
  "ismember",                    @() lbx_eq(logical([1 0 1 0 0 1]), ismember(mk(), {"red"}))
});
