lbx_run({
  "days_builds_a_duration",     @() lbx_type("duration", days(3))
  "days_reads_back",            @() lbx_near(3, days(days(3)))
  "hours_round_trip",           @() lbx_near(2, hours(hours(2)))
  "minutes_round_trip",         @() lbx_near(90, minutes(minutes(90)))
  "seconds_round_trip",         @() lbx_near(45, seconds(seconds(45)))
  "units_convert",              @() lbx_near(24, hours(days(1)))
  "minutes_to_seconds",         @() lbx_near(5400, seconds(minutes(90)))
  "addition",                   @() lbx_near(5, days(days(2) + days(3)))
  "subtraction",                @() lbx_near(1, days(days(3) - days(2)))
  "mixed_units_add",            @() lbx_near(26, hours(days(1) + hours(2)))
  "unary_minus",                @() lbx_near(-2, days(-days(2)))
  "abs",                        @() lbx_near(2, days(abs(-days(2))))
  "scaling_by_a_number",        @() lbx_near(6, days(days(2) * 3))
  "scaling_the_other_way",      @() lbx_near(6, days(3 * days(2)))
  "dividing_by_a_number",       @() lbx_near(1, days(days(3) / 3))
  "ratio_of_two_durations",     @() lbx_near(3, days(6) / days(2))
  "duration_times_duration_is_refused", @() lbx_error("duration:badProduct", @() days(2) * days(3))
  "comparison_lt",              @() lbx_true(hours(1) < days(1))
  "comparison_gt",              @() lbx_true(days(1) > minutes(59))
  "equality",                   @() lbx_true(hours(24) == days(1))
  "inequality",                 @() lbx_true(hours(23) ~= days(1))
  "explicit_unit_constructor",  @() lbx_near(90, minutes(duration(90, "minutes")))
  "bad_unit_rejected",          @() lbx_error("duration:badUnit", @() duration(1, "fortnights"))
  "bad_input_rejected",         @() lbx_error("days:badInput", @() days("three"))
  "char_renders_hms",           @() lbx_str_eq("02:00:00.00", char(hours(2)))
  "char_renders_days",          @() lbx_true(~isempty(strfind(char(days(2)), "2 days")))
  "negative_renders_with_sign", @() lbx_str_eq("-", char(-hours(2))(1))
});
