lbx_run({
  'report_counts_elements',    @() lbx_eq(4, array_report([1 2; 3 4]).n)
  'report_min_and_max',        @() lbx_eq([1 4], [array_report([1 2; 3 4]).mn array_report([1 2; 3 4]).mx])
  'report_mean',               @() lbx_near(2.5, array_report([1 2; 3 4]).avg)
  'report_class',              @() lbx_str_eq('double', array_report([1 2]).kind)
  'report_class_of_logical',   @() lbx_str_eq('logical', array_report([true false]).kind)
  'report_of_a_scalar',        @() lbx_eq(1, array_report(5).n)
  'report_of_empty_throws',    @() lbx_error('array_report:empty', @() array_report([]))
  'trim_drops_the_outlier',    @() lbx_eq([10 11 12 9], trim_outliers([10 11 12 9 200], 1))
  'trim_keeps_everything',     @() lbx_eq([1 2 3], trim_outliers([1 2 3], 5))
  'trim_keeps_a_constant',     @() lbx_eq([7 7 7], trim_outliers([7 7 7], 1))
  'trim_of_one_element',       @() lbx_eq(5, trim_outliers(5, 1))
  'trim_of_empty',             @() lbx_true(isempty(trim_outliers([], 1)))
  'trim_with_k_zero',          @() lbx_eq([5 5], trim_outliers([5 5], 0))
  'interleave_alternates',     @() lbx_eq([1 4 2 5 3 6], interleave([1 2 3], [4 5 6]))
  'interleave_of_one_each',    @() lbx_eq([1 2], interleave(1, 2))
  'interleave_returns_a_row',  @() lbx_eq([1 4], size(interleave([1 2], [3 4])))
  'interleave_takes_columns',  @() lbx_eq([1 3 2 4], interleave([1; 2], [3; 4]))
  'interleave_of_empty',       @() lbx_true(isempty(interleave([], [])))
  'interleave_checks_lengths', @() lbx_error('interleave:sizeMismatch', @() interleave([1 2], [1 2 3]))
});
