lbx_run({
  'normalise_lowers',            @() lbx_str_eq('ada', normalise_name('ADA'))
  'normalise_trims',             @() lbx_str_eq('ada', normalise_name('  ada  '))
  'normalise_collapses_spaces',  @() lbx_str_eq('ada lovelace', normalise_name('ada    lovelace'))
  'normalise_handles_tabs',      @() lbx_str_eq('a b', normalise_name(sprintf('a\t\tb')))
  'normalise_trims_then_collapses', @() lbx_str_eq('a b', normalise_name('   a   b   '))
  'normalise_of_empty',          @() lbx_str_eq('', normalise_name('   '))
  'normalise_leaves_clean_text', @() lbx_str_eq('ada lovelace', normalise_name('ada lovelace'))
  'extract_finds_one',           @() lbx_eq(42, extract_numbers('answer 42'))
  'extract_finds_several',       @() lbx_eq([1 2 3], extract_numbers('1 and 2 and 3'))
  'extract_reads_decimals',      @() lbx_near([1.5 2.25], extract_numbers('1.5 then 2.25'))
  'extract_reads_negatives',     @() lbx_eq([-7 3], extract_numbers('-7 up to 3'))
  'extract_finds_none',          @() lbx_true(isempty(extract_numbers('no digits here')))
  'extract_from_empty',          @() lbx_true(isempty(extract_numbers('')))
  'extract_ignores_surroundings',@() lbx_eq(12, extract_numbers('abc12def'))
  'extract_returns_numbers',     @() lbx_true(isnumeric(extract_numbers('1')))
  'initials_of_two_names',       @() lbx_str_eq('A.L', initials('ada lovelace'))
  'initials_of_three',           @() lbx_str_eq('A.L.K', initials('ada lovelace king'))
  'initials_of_one',             @() lbx_str_eq('A', initials('ada'))
  'initials_ignore_extra_spaces',@() lbx_str_eq('A.L', initials('  ada   lovelace  '))
  'initials_uppercase_already',  @() lbx_str_eq('A.L', initials('Ada Lovelace'))
  'initials_of_blank',           @() lbx_str_eq('', initials('   '))
  'initials_of_empty',           @() lbx_str_eq('', initials(''))
});
