lbx_run({
  'running_total_accumulates',  @() lbx_eq([1 3 6 10], running_total([1 2 3 4]))
  'running_total_of_one',       @() lbx_eq(5, running_total(5))
  'running_total_with_negatives', @() lbx_eq([1 -1 2], running_total([1 -2 3]))
  'running_total_of_empty',     @() lbx_true(isempty(running_total([])))
  'running_total_keeps_shape',  @() lbx_eq([3 1], size(running_total([1; 2; 3])))
  'normalise_maps_to_unit',     @() lbx_near([0 0.5 1], normalise([10 20 30]))
  'normalise_handles_negatives',@() lbx_near([0 1], normalise([-5 5]))
  'normalise_of_a_constant',    @() lbx_eq([0 0 0], normalise([7 7 7]))
  'normalise_of_one_element',   @() lbx_eq(0, normalise(3))
  'normalise_of_empty',         @() lbx_true(isempty(normalise([])))
  'pairwise_diff_is_shorter',   @() lbx_eq(3, numel(pairwise_diff([1 2 3 4])))
  'pairwise_diff_values',       @() lbx_eq([1 1 2], pairwise_diff([1 2 3 5]))
  'pairwise_diff_can_be_negative', @() lbx_eq(-3, pairwise_diff([5 2]))
  'pairwise_diff_of_one',       @() lbx_true(isempty(pairwise_diff(7)))
  'count_runs_counts_them',     @() lbx_eq(3, count_runs([1 1 2 2 2 3]))
  'count_runs_all_different',   @() lbx_eq(4, count_runs([1 2 3 4]))
  'count_runs_all_the_same',    @() lbx_eq(1, count_runs([9 9 9]))
  'count_runs_of_one',          @() lbx_eq(1, count_runs(5))
  'count_runs_of_empty',        @() lbx_eq(0, count_runs([]))
  'count_runs_returns_to_a_value', @() lbx_eq(3, count_runs([1 2 1]))
});
