long = [ones(1, 500), zeros(1, 300), 7, 7, ones(1, 200)];

lbx_run({
  'values_of_the_example',       @() lbx_eq([5 2 7], run_lengths([5 5 5 2 2 7]))
  'counts_of_the_example',       @() lbx_eq([3 2 1], counts_of([5 5 5 2 2 7]))
  'one_long_run_value',          @() lbx_eq(4, run_lengths([4 4 4 4]))
  'one_long_run_count',          @() lbx_eq(4, counts_of([4 4 4 4]))
  'no_repeats_values',           @() lbx_eq([1 2 3], run_lengths([1 2 3]))
  'no_repeats_counts',           @() lbx_eq([1 1 1], counts_of([1 2 3]))
  'a_value_that_returns',        @() lbx_eq([1 2 1], run_lengths([1 2 1]))
  'a_value_that_returns_counts', @() lbx_eq([1 1 1], counts_of([1 2 1]))
  'single_element_value',        @() lbx_eq(9, run_lengths(9))
  'single_element_count',        @() lbx_eq(1, counts_of(9))
  'empty_values',                @() lbx_eq(zeros(1, 0), run_lengths([]))
  'empty_counts',                @() lbx_eq(zeros(1, 0), counts_of([]))
  'negatives_and_fractions',     @() lbx_eq([-1 0.5], run_lengths([-1 -1 0.5]))
  'results_are_rows',            @() lbx_eq([1 3], size(counts_of([5 5 5 2 2 7])))
  'a_long_signal_values',        @() lbx_eq([1 0 7 1], run_lengths(long))
  'a_long_signal_counts',        @() lbx_eq([500 300 2 200], counts_of(long))
  'expand_the_example',          @() lbx_eq([5 5 5 2 2 7], expand_runs([5 2 7], [3 2 1]))
  'expand_one_run',              @() lbx_eq([4 4 4 4], expand_runs(4, 4))
  'expand_skips_a_zero_count',   @() lbx_eq([1 3 3], expand_runs([1 2 3], [1 0 2]))
  'expand_nothing',              @() lbx_eq(zeros(1, 0), expand_runs([], []))
  'expand_all_zero_counts',      @() lbx_eq(zeros(1, 0), expand_runs([1 2], [0 0]))
  'expand_is_a_row',             @() lbx_eq([1 6], size(expand_runs([5 2 7], [3 2 1])))
  'expand_too_few_counts',       @() lbx_error('expand_runs:size', @() expand_runs([1 2 3], [1 2]))
  'expand_too_many_counts',      @() lbx_error('expand_runs:size', @() expand_runs(1, [1 2]))
  'round_trip_example',          @() lbx_eq([5 5 5 2 2 7], round_trip([5 5 5 2 2 7]))
  'round_trip_long',             @() lbx_eq(long, round_trip(long))
  'round_trip_empty',            @() lbx_eq(zeros(1, 0), round_trip([]))
});
