lbx_run({
  'count_above_counts',          @() lbx_eq(2, count_above([1 5 3 9], 4))
  'count_above_is_strict',       @() lbx_eq(0, count_above([1 2 3], 3))
  'count_above_all_of_them',     @() lbx_eq(3, count_above([1 2 3], 0))
  'count_above_of_empty',        @() lbx_eq(0, count_above([], 0))
  'count_above_returns_a_number',@() lbx_true(isnumeric(count_above([1 2], 1)))
  'replace_negatives_replaces',  @() lbx_eq([3 0 4 0], replace_negatives([3 -1 4 -2], 0))
  'replace_negatives_with_any_value', @() lbx_eq([3 99], replace_negatives([3 -1], 99))
  'replace_negatives_leaves_zero',    @() lbx_eq([0 1], replace_negatives([0 1], 9))
  'replace_negatives_none_to_do',     @() lbx_eq([1 2], replace_negatives([1 2], 9))
  'replace_negatives_all_of_them',    @() lbx_eq([0 0], replace_negatives([-1 -2], 0))
  'replace_negatives_keeps_shape',    @() lbx_eq([2 1], size(replace_negatives([-1; 2], 0)))
  'select_range_is_inclusive',   @() lbx_eq([5 7 10], select_range([1 5 7 10 20], 5, 10))
  'select_range_matches_nothing',@() lbx_true(isempty(select_range([1 2], 10, 20)))
  'select_range_matches_all',    @() lbx_eq([1 2], select_range([1 2], 0, 10))
  'select_range_single_point',   @() lbx_eq(5, select_range([1 5 9], 5, 5))
  'first_above_finds_it',        @() lbx_eq(2, first_above([1 5 9], 4))
  'first_above_finds_the_first', @() lbx_eq(2, first_above([1 9 9], 4))
  'first_above_is_a_position',   @() lbx_eq(3, first_above([10 20 30], 25))
  'first_above_finds_nothing',   @() lbx_true(isempty(first_above([1 2], 10)))
  'first_above_of_empty',        @() lbx_true(isempty(first_above([], 0)))
});
