lbx_run({
  'load_drops_the_gap',        @() lbx_eq(7, height(load_typed('sensors.csv')))
  'load_keeps_the_columns',    @() lbx_eq(4, width(load_typed('sensors.csv')))
  'day_is_a_datetime',         @() lbx_type('datetime', load_typed('sensors.csv').Day)
  'station_is_categorical',    @() lbx_type('categorical', load_typed('sensors.csv').Station)
  'reading_is_numeric',        @() lbx_true(isnumeric(load_typed('sensors.csv').Reading))
  'quality_stays_text',        @() lbx_true(iscellstr(load_typed('sensors.csv').Quality))
  'dates_parsed_correctly',    @() lbx_eq(1, day(load_typed('sensors.csv').Day(1)))
  'busiest_is_south',          @() lbx_str_eq('south', busiest_station(load_typed('sensors.csv')))
  'busiest_returns_char',      @() lbx_true(ischar(busiest_station(load_typed('sensors.csv'))))
  'busiest_of_empty_throws',   @() lbx_error('busiest_station:empty', @() busiest_station(no_rows()))
  'window_is_inclusive',       @() lbx_eq(7, height(window_rows(load_typed('sensors.csv'), datetime(2026,1,1), datetime(2026,1,3))))
  'window_narrows',            @() lbx_eq(3, height(window_rows(load_typed('sensors.csv'), datetime(2026,1,1), datetime(2026,1,1))))
  'window_can_be_empty',       @() lbx_eq(0, height(window_rows(load_typed('sensors.csv'), datetime(2027,1,1), datetime(2027,1,2))))
  'window_returns_a_table',    @() lbx_type('table', window_rows(load_typed('sensors.csv'), datetime(2026,1,1), datetime(2026,1,1)))
  'window_keeps_the_columns',  @() lbx_eq(4, width(window_rows(load_typed('sensors.csv'), datetime(2026,1,1), datetime(2026,1,1))))
  'window_keeps_the_right_day',@() lbx_eq(2, day(window_rows(load_typed('sensors.csv'), datetime(2026,1,2), datetime(2026,1,2)).Day(1)))
  'window_on_day_two',         @() lbx_eq(2, height(window_rows(load_typed('sensors.csv'), datetime(2026,1,2), datetime(2026,1,2))))
  'unused_categories_survive', @() lbx_eq(3, numel(categories(load_typed('sensors.csv').Station)))
});
