lbx_run({
  'classify_all_three_ways',   @() lbx_eq({'negative', 'zero', 'positive'}, classify_all([-1 0 1]))
  'classify_keeps_the_shape',  @() lbx_eq([2 1], size(classify_all([1; 2])))
  'classify_returns_a_cell',   @() lbx_true(iscell(classify_all([1 2])))
  'classify_of_one',           @() lbx_str_eq('positive', classify_all(5){1})
  'classify_of_empty',         @() lbx_true(isempty(classify_all([])))
  'classify_fractions',        @() lbx_str_eq('negative', classify_all(-0.5){1})
  'safe_apply_maps',           @() lbx_eq([2 4 6], safe_apply(@(x) x * 2, [1 2 3]))
  'safe_apply_nan_on_failure', @() lbx_true(isnan(safe_apply(@positive_only, [1 -1 2])(2)))
  'safe_apply_keeps_the_rest', @() lbx_eq([1 2], safe_apply(@positive_only, [1 -1 2])([1 3]))
  'safe_apply_never_throws',   @() lbx_eq(3, numel(safe_apply(@positive_only, [-1 -2 -3])))
  'safe_apply_all_failed',     @() lbx_eq(3, sum(isnan(safe_apply(@positive_only, [-1 -2 -3]))))
  'safe_apply_keeps_the_shape',@() lbx_eq([2 1], size(safe_apply(@(x) x, [1; 2])))
  'safe_apply_of_empty',       @() lbx_true(isempty(safe_apply(@(x) x, [])))
  'safe_apply_rejects_vectors',@() lbx_true(isnan(safe_apply(@(x) [x x], 1)))
  'checked_mean_averages',     @() lbx_near(2, checked_mean([1 2 3]))
  'checked_mean_of_a_matrix',  @() lbx_near(2.5, checked_mean([1 2; 3 4]))
  'checked_mean_of_one',       @() lbx_near(5, checked_mean(5))
  'checked_mean_empty',        @() lbx_error('checked_mean:empty', @() checked_mean([]))
  'checked_mean_not_numeric',  @() lbx_error('checked_mean:notNumeric', @() checked_mean('abc'))
  'checked_mean_a_cell',       @() lbx_error('checked_mean:notNumeric', @() checked_mean({1}))
  'checked_mean_has_nan',      @() lbx_error('checked_mean:hasMissing', @() checked_mean([1 NaN 3]))
  'checked_mean_checks_in_order', @() lbx_error('checked_mean:empty', @() checked_mean(''))
});
