lbx_run({
  'valid_scores_pass',           @() lbx_true(validate_scores([0 50 100]))
  'one_score_is_fine',           @() lbx_true(validate_scores(50))
  'empty_is_rejected',           @() lbx_error('validate_scores:empty', @() validate_scores([]))
  'text_is_rejected',            @() lbx_error('validate_scores:notNumeric', @() validate_scores('abc'))
  'a_cell_is_rejected',          @() lbx_error('validate_scores:notNumeric', @() validate_scores({1}))
  'too_high_is_rejected',        @() lbx_error('validate_scores:outOfRange', @() validate_scores([1 300]))
  'too_low_is_rejected',         @() lbx_error('validate_scores:outOfRange', @() validate_scores([-1 50]))
  'boundaries_are_allowed',      @() lbx_true(validate_scores([0 100]))
  'empty_is_checked_first',      @() lbx_str_eq('validate_scores:empty', error_id_of(@() validate_scores([])))
  'try_parse_reads_a_number',    @() lbx_near(3.5, parsed_value('3.5'))
  'try_parse_reports_success',   @() lbx_true(parsed_ok('3.5'))
  'try_parse_ignores_spaces',    @() lbx_near(42, parsed_value('  42  '))
  'try_parse_reads_a_negative',  @() lbx_near(-7, parsed_value('-7'))
  'try_parse_fails_on_words',    @() lbx_false(parsed_ok('abc'))
  'try_parse_value_on_failure',  @() lbx_eq(0, parsed_value('abc'))
  'try_parse_fails_on_empty',    @() lbx_false(parsed_ok(''))
  'try_parse_fails_on_a_number', @() lbx_false(parsed_ok(5))
  'try_parse_does_not_throw',    @() lbx_str_eq('', error_id_of(@() try_parse('nonsense')))
  'error_id_of_reports_the_id',  @() lbx_str_eq('a:b', error_id_of(@() error('a:b', 'boom')))
  'error_id_of_on_success',      @() lbx_str_eq('', error_id_of(@() 1 + 1))
  'error_id_of_catches_builtin', @() lbx_true(~isempty(error_id_of(@() undefined_function_xyz())))
});
