lbx_run({
  'in_range_keeps_the_middle',      @() lbx_eq([2 3], in_range([1 2 3 4], 2, 3))
  'in_range_includes_both_ends',    @() lbx_eq([5 7 5], in_range([5 -1 7 5], 5, 7))
  'in_range_keeps_order',           @() lbx_eq([9 3 6], in_range([9 12 3 0 6], 1, 10))
  'in_range_everything',            @() lbx_eq([1 2 3], in_range([1 2 3], -100, 100))
  'in_range_nothing_is_an_empty_row', @() lbx_eq(zeros(1, 0), in_range([1 2 3], 10, 20))
  'in_range_of_empty',              @() lbx_eq(zeros(1, 0), in_range(zeros(1, 0), 0, 1))
  'in_range_single_value_band',     @() lbx_eq([4 4], in_range([4 5 4 3], 4, 4))
  'in_range_drops_nan',             @() lbx_eq([1 2], in_range([1 NaN 2], 0, 5))
  'in_range_with_fractions',        @() lbx_eq([0.5 1.5], in_range([0.5 1.5 2.5], 0.5, 2))
  'mean_skips_nan',                 @() lbx_near(6, valid_mean([4 NaN 8]))
  'mean_without_gaps',              @() lbx_near(2.5, valid_mean([1 2 3 4]))
  'mean_of_one',                    @() lbx_near(7, valid_mean([NaN 7 NaN]))
  'mean_of_all_nan_is_zero',        @() lbx_eq(0, valid_mean([NaN NaN]))
  'mean_of_empty_is_zero',          @() lbx_eq(0, valid_mean([]))
  'mean_of_negatives',              @() lbx_near(-2, valid_mean([-1 NaN -3]))
  'count_skips_nan',                @() lbx_eq(2, count_valid([4 NaN 8]))
  'count_without_gaps',             @() lbx_eq(4, count_valid([1 2 3 4]))
  'count_of_all_nan',               @() lbx_eq(0, count_valid([NaN NaN]))
  'count_of_empty',                 @() lbx_eq(0, count_valid([]))
});
