lbx_run({
  'load_drops_the_gap_row',     @() lbx_eq(7, height(load_readings('sensors.csv')))
  'load_keeps_every_column',    @() lbx_eq(4, width(load_readings('sensors.csv')))
  'day_became_a_datetime',      @() lbx_type('datetime', load_readings('sensors.csv').Day)
  'station_became_categorical', @() lbx_type('categorical', load_readings('sensors.csv').Station)
  'reading_stayed_numeric',     @() lbx_true(isnumeric(load_readings('sensors.csv').Reading))
  'the_dates_parsed',           @() lbx_eq(2026, year(load_readings('sensors.csv').Day(1)))
  'three_stations_remain',      @() lbx_eq(3, numel(categories(load_readings('sensors.csv').Station)))
  'summary_has_one_row_each',   @() lbx_eq(3, height(daily_summary(load_readings('sensors.csv'))))
  'summary_carries_counts',     @() lbx_eq(7, sum(daily_summary(load_readings('sensors.csv')).GroupCount))
  'summary_names_the_mean',     @() lbx_true(any(strcmp('mean_Reading', daily_summary(load_readings('sensors.csv')).Properties.VariableNames)))
  'summary_computes_the_mean',  @() lbx_near(13.5, mean_for('north'))
  'summary_of_another_station', @() lbx_near(10, mean_for('east'))
  'report_counts_the_readings', @() lbx_true(~isempty(strfind(report_line(load_readings('sensors.csv')), '7 readings')))
  'report_counts_the_stations', @() lbx_true(~isempty(strfind(report_line(load_readings('sensors.csv')), '3 stations')))
  'report_names_the_highest',   @() lbx_true(~isempty(strfind(report_line(load_readings('sensors.csv')), 'south')))
  'report_formats_one_decimal', @() lbx_true(~isempty(strfind(report_line(load_readings('sensors.csv')), '19.3')))
  'report_is_char',             @() lbx_true(ischar(report_line(load_readings('sensors.csv'))))
  'report_of_nothing',          @() lbx_str_eq('no readings', report_line(empty_readings()))
});
