lbx_run({
  'take_first_takes_from_the_front', @() lbx_eq([1 2 3], take_first([1 2 3 4 5], 3))
  'take_first_of_one',               @() lbx_eq(1, take_first([1 2 3], 1))
  'take_first_of_all',               @() lbx_eq([1 2], take_first([1 2], 2))
  'take_first_of_none',              @() lbx_true(isempty(take_first([1 2], 0)))
  'take_first_past_the_end',         @() lbx_error('take_first:tooMany', @() take_first([1 2], 5))
  'take_last_takes_from_the_back',   @() lbx_eq([4 5], take_last([1 2 3 4 5], 2))
  'take_last_of_one',                @() lbx_eq(5, take_last([1 2 3 4 5], 1))
  'take_last_of_all',                @() lbx_eq([1 2], take_last([1 2], 2))
  'take_last_past_the_end',          @() lbx_error('take_last:tooMany', @() take_last([1 2], 5))
  'every_other_odd_length',          @() lbx_eq([1 3 5], every_other([1 2 3 4 5]))
  'every_other_even_length',         @() lbx_eq([1 3], every_other([1 2 3 4]))
  'every_other_of_one',              @() lbx_eq(7, every_other(7))
  'every_other_of_empty',            @() lbx_true(isempty(every_other([])))
  'swap_ends_swaps',                 @() lbx_eq([5 2 3 4 1], swap_ends([1 2 3 4 5]))
  'swap_ends_of_two',                @() lbx_eq([2 1], swap_ends([1 2]))
  'swap_ends_of_one',                @() lbx_eq(9, swap_ends(9))
  'swap_ends_leaves_input_alone',    @() lbx_eq([1 2 3], untouched())
  'works_on_a_column',               @() lbx_eq([1; 2], take_first([1; 2; 3], 2))
});
